import { EdgeType } from '../types';

interface RelationshipBadgeProps {
  type: EdgeType;
}

const relationshipLabels: Record<EdgeType, string> = {
  'contributes_to': 'Contributes',
  'created_from': 'Created From',
  'relates_to': 'Related',
  'references': 'References',
  'generated_by': 'Generated By',
  'affects': 'Affects',
};

export const RelationshipBadge = ({ type }: RelationshipBadgeProps) => {
  return (
    <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800">
      {relationshipLabels[type] || type}
    </span>
  );
};
